### ISSUE TITLE
dupRadar seems to depend upon `KernSmooth` but is not listed in package dependencies

### ISSUE THREAD

**Issue by mattheiter** [ssayols/dupRadar#3]
See discussion here: https://github.com/bioconda/bioconda-recipes/issues/8341

Resolution: add `KernSmooth` as a dependency to `dupRadar` as `KernSmooth` is part of `r-recommended` but not `r-base`,

**Comment by ssayols** [comment]
Hi @matdoering, thanks for reporting the issue.
Looks like `dupRadar` is indirectly using `KernSmooth` when calling `grDevices::densCols()`.
Instead of simply patching the package `DESCRIPTION`, I'll write proper `roxygen` `@import` tags. And propagate the changes to Bioconductor release and devel.

**Comment by ssayols** [comment]
Added `KernSmooth` as an `IMPORT` in `DESCRIPTION` for Bioconductor release (3.15). Should be available sometime tomorrow.
For the next Bioconductor release, proper `roxygen` `@import` tags have been added.
