### ISSUE TITLE
Facing problem in interpreting plots

### ISSUE THREAD

**Issue by Rohit-Satyam** [ssayols/dupRadar#4]
Hi!!

I am trying to use dupradar to check the duplication rate in one of the plasmodium publically available dataset. I mark duplicates using picard MarkDuplicates. The data is singleEnd and reverse stranded. I got the following plots.
My queries are:

1. For this sample what does each dot in the density dotplot represents? Genes? Also does the distance of the dot's from the curve mean anything? Is this sample good to go with?
2.  The red and the yellow region in my plot falls between 50-75% duplication rate!! Is this rate acceptable.
3. What is the utility of box plot. I believe it just tells us about the average expression (in RPKM) for genes that show duplicate rate between 5% difference interval. Wouldn't a violion plot with perhaps scatter/box plot be more helpful to see if genes showing excessive duplication rate are more or less maybe. Just thinking!!

![image](https://user-images.githubusercontent.com/55479480/184266313-bf4af46e-e322-4fff-b25b-af2a5a585f8a.png)
![image](https://user-images.githubusercontent.com/55479480/184266331-b78e9981-6e3f-44cf-b4db-18b01d80cb3a.png)

**Comment by ssayols** [comment]
Hi Rohit,
since your problem is not related with dupRadar's development per se, please let me point you to the [Bioconductor's support forum](https://support.bioconductor.org/). There you can get help from others within your field of expertise, as well as help others with your posts.
